function [ flag ] = isKinectDataset( settings )
%ISKINECTDATASET Return true if we are runninng tests on a Kinect dataset
%   Detailed explanation goes here

if strcmp(settings.dataset, 'test_data') ...
        || strcmp(settings.dataset, 'ZED') ...
        || strcmp(settings.dataset, 'pwlinear_nbCorners=10') ...
    flag = false;
elseif strcmp(settings.dataset, 'lids_floor7') ...
        || strcmp(settings.dataset, 'lids_floor6') ...
        || strcmp(settings.dataset, 'lab1') ...
        || strcmp(settings.dataset, '38_floor3') ...
        || strcmp(settings.dataset, '39_floor3') ...
        || strcmp(settings.dataset, 'stata_floor1') ...
        || strcmp(settings.dataset, '34_floor3') ...
        || strcmp(settings.dataset, '36_floor3') ...
        || strcmp(settings.dataset, '32_144') 
    flag = true;
else
    error('error in function isKinectDataset(): unknown dataset type');
end

